### ISSUE TITLE
Dir Listing

### ISSUE THREAD

**Issue by vinipsmaker** [bagder/docs#1]
On the [FTP vs HTTP document](https://daniel.haxx.se/docs/ftp-vs-http.html), it's noted that "_FTP has for example commands for listing dir contents of the remote server, while HTTP has no such concept_".

I did read the HTTP spec and I know it hasn't this concept.

I haven't read the FTP spec nor the WebDAV spec, so I cannot make any statements about them. However, are you sure directory listing cannot be accomplished using WebDAV? [RFC4918 states](https://tools.ietf.org/html/rfc4918):

> Collections: The ability to create sets of documents and to retrieve a hierarchical membership listing (like a directory listing in a file system).

I'll take a better look at WebDAV once Boost ship some XML library, but until there I have very little interest in studying WebDAV. I hope you forgive me for being that lazy.

If WebDAV does allow dir listing, I think it'd be appropriate to note it on the "_Dir Listing_" section of the HTTP vs FTP document.

**Comment by bagder** [comment]
I know WebDAV offers several "FTP-like" abilities, and I mention it briefly under the "Upload" title. But WebDAV is a protocol in itself, on top of HTTP, so it would not be a fair comparison. That would be an excellent point for the "FTP vs WebDAV" article. But that's not for me to write.

Maybe I should add something generic in that style about WebDAV at the top...

**Comment by vinipsmaker** [comment]
> I know WebDAV offers several "FTP-like" abilities, and I mention it briefly under the "Upload" title.

Yes, and this tricked me to think that WebDAV would only have alternatives to work with files but not dirs (including dir listing).

Maybe move WebDAV to its own section and cite it there as a way to work around some of the HTTP limitations would trick less users.

What do you think?
