### ISSUE TITLE
bittorrent vs HTTP => missing "Lora" font reference

### ISSUE THREAD

**Issue by spacegaier** [bagder/docs#14]
Really minuscule note: The "bittorrent vs HTTP" and the "Encrypted Transfer Protocols Compared" pages are using "Arial" where as all (?) other pages are consistent with "Lora".

Missing in the HTML header: 
`<link href="//fonts.googleapis.com/css?family=Lora" rel="stylesheet" type="text/css">`

**Comment by bagder** [comment]
Thanks, fixed now!
