### ISSUE TITLE
curl vs httpie — request data

### ISSUE THREAD

**Issue by jakubroztocil** [bagder/docs#17]
Hi @bagder, thanks for curl and for your "curl vs HTTPie" comparison page (https://daniel.haxx.se/docs/curl-vs-httpie.html). I have a small clarification:

> cURL
> ∙ can send binary POSTs

> HTTPie
> ∙  Assumes "name=value" for POSTS (name:value or just "data" is hard/impossible to send, not to mention POSTing Connection: - which instead will be intepreted as remove that header please)

[HTTPie uses `stdin` for unstructured request data](https://httpie.org/doc#redirected-input), for example:

```bash
$ echo name:value | http httpbin.org/post
$ echo data | http PUT httpbin.org/put
$ echo Connection: | http PATCH httpbin.org/patch
$ http POST httpbin.org/post < /some/binary/file
```

**Comment by bagder** [comment]
Thanks, sorry it took me this long to update! :-(

**Comment by jakubroztocil** [comment]
Thanks, @bagder. 

Last thing:

> not to mention POSTing Connection: - which instead will be intepreted as remove that header please

There is nothing preventing you from this (or any other) data using the mechanism which httpie provides:

```bash
$ echo Connection: | http PATCH httpbin.org/patch
```

**Comment by bagder** [comment]
I think that's what it says now: that you have to pass that to stdin to send it and not as an argument, as then it will have (unexpected) side-effects. Do you think I should phrase it differently?
