### ISSUE TITLE
URL-interop: issue with fragments and data: URLs

### ISSUE THREAD

**Issue by rocallahan** [bagder/docs#18]
You say there are no known issues with fragments. There is a disagreement among browsers about the treatment of # in data: URLs. The spec, and most browsers, say that the fragment starts at the first #. Webkit treats # as part of the data, although that may change soon. No idea what other URL processors do!
See https://bugs.webkit.org/show_bug.cgi?id=68089

**Comment by bagder** [comment]
Ugh, what fun "feature". The question is *possibly* if this is actually an interop problem or a plain webkit bug... I think about adding a text like this for my "fragments" section. What do you think?

> Web browsers have not decided entirely on how fragments work, at least not for
`data:` URLs. Should they support framgments or not? [Webkit](https://bugs.webkit.org/show_bug.cgi?id=68089) differs from the others.

**Comment by rocallahan** [comment]
Sounds reasonable.

> The question is possibly if this is actually an interop problem or a plain webkit bug...

That is in the eye of the beholder. I think technically it is a plain Webkit bug, but the difference has existed for a long time.

**Comment by bagder** [comment]
Yeah, having it around that long probably qualifies it as an interop issue. I've added a mention in the doc now. thanks!
