### ISSUE TITLE
cget - competition to wget :)

### ISSUE THREAD

**Issue by shevegen** [bagder/docs#3]
I read your recent article.

I am notoriously lazy (and I don't know much at all).

Wget I am using a lot because "wget url" is so simple. I did not even know that you could use curl with an option to achieve the same, but perhaps the thing is that curl with an option may be slightly harder to type/use, so I suggest cget binary. :) That means that "cget url" should do what "wget url" does, at the least as download from a remote file.

Perhaps optionally as a compile-time option to configure, if people don't want "cget" it by default or so.

Anyway not sure if this is the wrong issue request, sorry; I just was linked to the page from the article itself, otherwise I would have filed for curl itself. Feel free to close this at any time if it seems not fit to curl! Thanks.

**Comment by bagder** [comment]
Thank! While I agree that it would be an easy way to fix  the "but -O is too hard to type" argument, I don't think it is worth the documentation effort to make a separate binary for that reason alone. Anyone who'd think that was a real deal-breaker could write an alias or script to do this already.
