### ISSUE TITLE
wget cannot do digest authentication against proxy server (only http server auth digest)

### ISSUE THREAD

**Issue by mmokrejs** [bagder/docs#6]
Hi Daniel,
  an interesting read at https://daniel.haxx.se/docs/curl-vs-wget.html. But it seems `wget` can do digest authentication:

```
       --http-user=user
       --http-password=password
           Specify the username user and password password on an HTTP server.  According to the type of the challenge, Wget will encode them using either the "basic" (insecure), the "digest", or the Windows "NTLM" authentication scheme.

           Another way to specify username and password is in the URL itself.  Either method reveals your password to anyone who bothers to run "ps".  To prevent the passwords from being seen, store them in .wgetrc or .netrc, and make sure to protect those files from other users with
           "chmod".  If the passwords are really important, do not leave them lying in those files either---edit the files and delete them after Wget has started the download.
```

But I am especially confused with the `wget –auth-no-challenge` usage/syntax that I cannot myself force wget to try digest against a remote proxy server at the moment myself. :( Hmm, maybe 1.12 on the server is too old (and I read manpage for 1.18). :-((

**Comment by bagder** [comment]
The key there is **over HTTP proxy**. The options you mention are for **an HTTP server**. Those are done independently of each other.

I don't think wget supports digest for HTTP proxies even in the latest versions. Or am I wrong?

**Comment by rockdaboot** [comment]
I am unsure - I never use a proxy.
Aren't there many different kinds of proxies ? E.g. transparent proxies should work, Tor/SOCKS5 needs an external wrapper (e.g. tsocks/torsocks) since wget doesn't support SOCKS directly.
There is a script `contrib/tsocked-wget` that you can have a look at.

**Comment by bagder** [comment]
There are indeed many kinds of proxies but in the doc I specifically say "HTTP proxy" which is intended to clarify that I speak of authentications against HTTP proxies.

SOCKS is another kind (or kind**s** really) of proxy and curl's native support for that is also mentioned in the document.

**Comment by mmokrejs** [comment]
OK, thank you for clarification, I indeed missed the point it was a section about HTTP auth only. If you can improve the manpage it would be nice. I care at the moment only about squid proxy server and authentication against it using either basic or digest auth. In general, it would be helpful to write a comparison document about wget vs. curl capabilities as it seems this is still quite unexplored and incomplete.

I got to this because we want to block trojans and "call-home" features of softwares on a cluster, so a simple approach like Basic auth is enough.

**Comment by bagder** [comment]
> it would be helpful to write a comparison document about wget vs. curl capabilities as it seems this is still quite unexplored and incomplete.

I don't understand. Isn't that exactly what this document is? Comparisons of curl vs wget doesn't seem on topic for either curl's nor wget's man pages.

**Comment by mmokrejs** [comment]
But if you look for proxy-related information in the document, there is just the SOCKS-related line, and that is all. If we speak, as in my case, in a user's perspective about proxy server support and we want to read about basic/auth/NTLM/kerberos/ldap support in either of the tools, there the document does not say anything about that. I as a user care about a proxy-supports for htpp/https/ftp protocols at least, and wonder whether curl or wget is better to use against say squid server, and what it need to be setup on squid's side.

**Comment by bagder** [comment]
The proxy line and the HTTP proxy mention on the line above, yes. Because those are the differences I'm aware of. If you know others or can think of a better way to express the differences then please by all means help me do that! I'm all for improving docs, all over.

> wonder whether curl or wget is better to use against say squid server

But that's a very specific request. I prefer to have this document just clearly spell out what different features or behaviors the tools do and offer, and then each reader can use that information as they see fit and base their own opinion of what to use for that purpose.

But again, if you think you can express that in way so the information gets better, clearer or easier to  grasp then I'm very willing to listen to your suggestion!

**Comment by mmokrejs** [comment]
I would be happy to contribute my expertise in this but unfortunately, my knowledge is just zero. I only wanted to emphasize the existing document doe snot answer my questions and that is why I thought yet another document would be more helpful for my purposes. I certainly care more whether I should "bother" to configure my wget or curl settings to plays with my squid server, and want to be sure that will work with all (http, https, ftp) protocols.

Feel free to edit the title of this issues, or even close it as invalid. The main what I learned is that wget cannot do digest auth against the squid proxy. Thank you.

**Comment by rockdaboot** [comment]
Just searched the wget source code and confirm that wget does not react on 407 response code. Proxy authorization is done with 'Basic' only (if user/pw is given). The code for 'Digest' exists, but the 'glue' seems missing.
I guess, nobody ever asked for that feature - it wouldn't be a big deal to create the missing 'glue' code.

**Comment by mmokrejs** [comment]
IMHO adding digest auth to wget proxy auth would be very helpful.
