### ISSUE TITLE
URL-interop.md: Distinguish between human-provided and producer-provided input

### ISSUE THREAD

**Issue by rockdaboot** [bagder/docs#8]
This should be made very clear.

Any tool that accepts user/human provided data normally has some kind of 'acceptance' layer, which of course differs from tool to tool. E.g. what I type into a browser's URL field doesn't need to be a technically correct URL. It could be a domain without scheme, a wrongly written scheme (e.g. htp://) or even some kind of shortcuts ('gl' for https://google.com/). As a 'dumb' user I expect the browser to do the 'right' thing, e.g. prepend https:// (not http:// !), correcting htp to http, expanding the shortcut.

Command line tools like wget or curl will (and should !) behave differently - they have to be aware that correcting user input and continue might be *very* dangerous (e.g. when using such a tool as root). I also expect these tools being used by more sensible people - at least the 'command line hurdle' has been taken.

And than we have URLs coming from producers (HTML tools, scripts, programs, ...). And IMO, these kind of URLs should be treated technically correct as by RFC. At least by non-browsers (sensible user argument above). That might break some (hand-written ?) HTML - but hey - the understandable user sees the problem and could blame the source of it. That is more than an average browser-user can do - it would be deadly for browser vendors having 100 thousands of people who blame them for incompetence.

I see browsers and CLI tools having a different audience and thus have (slightly) different demands regarding handling URLs (in this context). Why should a CLI tool accept broken URLs (regarding RFCs) at all ? Browser will be more relaxed of course, but should IMO not try to establish a new URL standard besides the IETF/RFCs. Nothing against a recommendation on how to handle URLs as a browser - but that is not (or just partly) relevant for CLI tools (or even producer tools !).

URL-interop.md could clearly say how (and why) browsers and CLI tools do certain things differently.
And analyzing what compromises could be made to get URL interpretation as close as possible together between these different type of applications.

**Comment by bagder** [comment]
Right, we should make it clear that by "URL" we don't mean what you enter in the address bar of your favorite browsers. The URL fields are UI and they do magic stuff. We should talk about URLs as passed over the wire, sent in `Location:` headers or that are programmatically passed into APIs.

Any suggestions on how we best express this?

I think a reason why URLs have eroded on the Internet over time from the stricter RFC 3986 style to the current state, is that URLs are entered and passed around by humans and as humans make mistakes, the browsers have adapted and tried to accommodate to that. "The robustness principle" if you want.

**Comment by bagder** [comment]
Something like this?

`"URL" (in the scope of this document) refers to the sequence of characters passed into APIs, sent over the network and passed from machine to machine. It does not necessarily match what typical browsers accept or support in their GUI address bars.`

**Comment by rockdaboot** [comment]
Sounds good to me !

**Comment by bagder** [comment]
Thanks, fixed in 8cf611cce37c0
